on: 
  push:
    branches:
     - master
jobs:
  run_tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      run: |
         chmod +x ./public/scripts/test.sh
         export GIT_MERGE_AUTOEDIT=no
         sudo apt-get install git -y
         git config --global user.name "saiboby"
         git config --global user.email "saibabu.tan@gmail.com"
         git config --list
         cd /opt
         git clone https://github.com/saiboby/mainservice.git
         cd mainservice
         git checkout master
         git remote add service1 https://github.com/saiboby/service1.git
         git subtree pull --prefix=demo1 service1 master
         #git push https://github.com/saiboby/mainservice.git master
         git push https://saiboby:${{ secrets.GITHUB_TOKEN }}@github.com/saiboby/service1.git master
      shell: bash
     
